    development:
      adapter: mysql2
      database: furnilac_app_reza_development
      username: root
      password: root
      host: localhost
    test:
      adapter: mysql2
      database: furnilac_app_reza_test
      username: root
      password: root
      host: localhost
    production:
      adapter: mysql2
      database: furnilac_app_reza_production
      username: root
      password: root
      host: localhost
